In [3]:
import pandas as pd

from pathlib import Path

### Load Scores

In [4]:
exercise_path = Path("course_directory/ads_exercise")
output_path = Path("total_score")

In [5]:
scores = pd.read_csv(exercise_path.joinpath("grades.csv"))
scores.head()

,assignment,duedate,timestamp,student_id,last_name,first_name,email,raw_score,late_submission_penalty,score,max_score
0,04_python_basics_III,NaN,NaN,theresanadler,NaN,NaN,NaN,0.0,0.0,0.0,10.0
1,04_python_basics_III,NaN,NaN,moestenfau,NaN,NaN,NaN,0.0,0.0,0.0,10.0
2,04_python_basics_III,NaN,NaN,lucaabel,NaN,NaN,NaN,6.5,0.0,6.5,10.0
3,04_python_basics_III,NaN,NaN,moesten,NaN,NaN,NaN,0.0,0.0,0.0,10.0
4,04_python_basics_III,NaN,NaN,AhmedSofan10,NaN,NaN,NaN,8.0,0.0,8.0,10.0

In [6]:
score_long = scores.set_index(["student_id", "assignment"]).sort_index()
score_long

                                   duedate  timestamp  last_name  first_name  \
student_id   assignment
AhmedSofan10 04_python_basics_III      NaN        NaN        NaN         NaN
             05_dicts_classes          NaN        NaN        NaN         NaN
             06_numpy_scipy            NaN        NaN        NaN         NaN
             07_pandas                 NaN        NaN        NaN         NaN
             08_statistics             NaN        NaN        NaN         NaN
...                                    ...        ...        ...         ...
yp69ejot     09-visualization          NaN        NaN        NaN         NaN
             10-ml                     NaN        NaN        NaN         NaN
             ads_assignment_1          NaN        NaN        NaN         NaN
             ads_assignment_2          NaN        NaN        NaN         NaN
             ads_assignment_3          NaN        NaN        NaN         NaN

                                   email  raw_score  late_submission_penalty  \
student_id   assignment
AhmedSofan10 04_python_basics_III    NaN        8.0                      0.0
             05_dicts_classes        NaN       13.0                      0.0
             06_numpy_scipy          NaN       10.0                      0.0
             07_pandas               NaN        9.0                      0.0
             08_statistics           NaN       11.0                      0.0
...                                  ...        ...                      ...
yp69ejot     09-visualization        NaN       11.0                      0.0
             10-ml                   NaN       17.0                      0.0
             ads_assignment_1        NaN        1.0                      0.0
             ads_assignment_2        NaN        8.0                      0.0
             ads_assignment_3        NaN       10.0                      0.0

                                   score  max_score
student_id   assignment
AhmedSofan10 04_python_basics_III    8.0       10.0
             05_dicts_classes       13.0       13.0
             06_numpy_scipy         10.0       10.0
             07_pandas               9.0       12.0
             08_statistics          11.0       11.0
...                                  ...        ...
yp69ejot     09-visualization       11.0       11.0
             10-ml                  17.0       19.0
             ads_assignment_1        1.0        1.0
             ads_assignment_2        8.0        8.0
             ads_assignment_3       10.0       10.0

[640 rows x 9 columns]

In [8]:
sum_points = score_long["score"].unstack("assignment").sum(axis=1)
sum_points

student_id
AhmedSofan10     92.0
ArefehRh         51.0
Ashikluffy        1.0
Chamutalcast      9.0
Dan-github16      1.0
                ...
viranya31         1.0
vv88alias       104.0
xindiyu         101.0
youssafB          0.0
yp69ejot        101.0
Length: 64, dtype: float64

In [6]:
max_score = score_long.xs(score_long.index[0][0], level="student_id")["max_score"].sum() # select the first student
max_score

105.0

In [12]:
# set this manually, when the score is not right
max_score = 100.0

In [13]:
percentage = (sum_points / max_score) * 100 
percentage[percentage > 100] = 100
percentage = percentage.sort_values(ascending=False)

In [14]:
percentage.head(20)

student_id
yp69ejot             100.0
PaulaLim             100.0
xindiyu              100.0
vv88alias            100.0
raihansaa            100.0
nickrpr              100.0
ly87muro             100.0
Gschosi              100.0
lamteteeow           100.0
charlottewiebecke    100.0
AhmedSofan10          92.0
suchirasuresh         85.0
MakitaNdunguru        85.0
luzrch                82.0
sriboote              82.0
MichaelaHofmann       80.0
abdallaheid00         75.0
lucaabel              69.5
SusanneMa             66.5
theoneandvronly       62.0
dtype: float64

In [10]:
percentage.hist(bins=20)

NameError: name 'percentage' is not defined

In [9]:
import time

semester = "SoSe_23"

# export csv
timestr = time.strftime("%Y%m%d-%H%M%S")
percentage.to_csv(output_path.joinpath(semester+"-"+timestr+".csv"))

NameError: name 'percentage' is not defined

In [24]:
idm_list = pd.read_csv("course_directory/classroom_roster.csv").loc[:,["identifier", "github_username"]]
idm_list

   identifier github_username
0    ab99xxxx   theresanadler
1    af31yxin  niculinadragan
2    ak38ryxi        NavalMor
3    al11ytyw         Gschosi
4    al48owam             NaN
..        ...             ...
86   ys28odyp             NaN
87   ys61uqym         h4xl33t
88   yv49alyr      moestenfau
89   yx26enos         smokemh
90   za07ryma    AhmedSofan10

[91 rows x 2 columns]

In [25]:
idm_list.set_index("github_username", inplace=True)
idm_list.index.name = "student_id"

In [26]:
idm_list

               identifier
student_id
theresanadler    ab99xxxx
niculinadragan   af31yxin
NavalMor         ak38ryxi
Gschosi          al11ytyw
NaN              al48owam
...                   ...
NaN              ys28odyp
h4xl33t          ys61uqym
moestenfau       yv49alyr
smokemh          yx26enos
AhmedSofan10     za07ryma

[91 rows x 1 columns]

In [31]:
# join percentage and idm_list

total = pd.DataFrame(percentage, columns=["score_percent"]).join(idm_list, how="inner")
total

              score_percent identifier
student_id
AhmedSofan10           92.0   za07ryma
ArefehRh               51.0   ju47kato
Ashikluffy              1.0   ix31ipix
Chamutalcast            9.0   sy23hoza
Dan-github16            1.0   na30dopa
...                     ...        ...
viranya31               1.0   yq13isef
vv88alias             100.0   we70xebi
xindiyu               100.0   vo28hudo
youssafB                0.0   ok13qina
yp69ejot              100.0   yp69ejot

[63 rows x 2 columns]

In [36]:
# drop all rows with identifier length > 8 

total.drop(total[total['identifier'].str.len() > 8].index, inplace = True)

In [37]:
total

                   score_percent identifier
student_id
AhmedSofan10                92.0   za07ryma
ArefehRh                    51.0   ju47kato
Ashikluffy                   1.0   ix31ipix
Chamutalcast                 9.0   sy23hoza
Dan-github16                 1.0   na30dopa
EmilyKratsch                59.0   go63gaxo
FA-538                      42.0   lo27cyru
Gschosi                    100.0   al11ytyw
Jonas185                    24.0   aq28onip
KayranX                      9.0   sa58juwu
LinusRac                    57.0   ik94foow
Lukaaaa13                   62.0   ku05zuji
MakitaNdunguru              85.0   uk68iduv
Melina2312                  19.0   tu51vibo
MichaelaHofmann             80.0   ro54hiqu
MokshaVora29                53.5   je54luly
NTKL                         1.0   hi25numi
NavalMor                     9.0   ak38ryxi
Nelles256                   21.0   ni38doqy
Olgaspice                    9.0   am42ybuv
PaulaLim                   100.0   ly44qone
Pei-HanJiang                60.0   pe39toqa
SusanneMa                   66.5   xi46feza
abdallaheid00               75.0   ez72oxib
abdulmoeed786-ger            9.0   if21eseh
aleemfau                     0.0   ty28vipo
alisag12                    10.5   uk68ebih
charlottewiebecke          100.0   if80ajil
deerson2                    22.5   hi60quti
h4xl33t                      9.0   ys61uqym
heenas085                    0.0   fa75kyqy
konichua                    38.0   il71ywod
ksfjfo                      33.5   qe72syka
lamteteeow                 100.0   ga45wapo
leopotato721                 9.0   ja62sysi
luzrch                      82.0   ew73ugaf
ly87muro                   100.0   ly87muro
michi1248                   19.0   ra99topo
miculm                      22.5   ep70ujin
mirikurz                    24.0   an89ibyq
moestenfau                  11.0   yv49alyr
nickrpr                    100.0   ta08goje
niculinadragan              14.5   af31yxin
nilamrajakk311              21.0   uj46yrof
nurulkabir99                46.0   he09gyta
osddq                        9.0   he82luta
priyam1504                   1.0   mo58ruxy
raihansaa                  100.0   fu40panu
skbabeer                     9.0   eb37yzyp
smokemh                     19.0   yx26enos
sriboote                    82.0   ib35olyr
suchirasuresh               85.0   yh07ajaw
susmaraifau                  1.0   ri32luvi
theresanadler               10.0   ab99xxxx
urschade                     0.0   us52odab
viranya31                    1.0   yq13isef
vv88alias                  100.0   we70xebi
xindiyu                    100.0   vo28hudo
youssafB                     0.0   ok13qina
yp69ejot                   100.0   yp69ejot

In [39]:
total = total.reset_index().set_index("identifier").drop("student_id", axis=1).sort_index()
total

            score_percent
identifier
ab99xxxx             10.0
af31yxin             14.5
ak38ryxi              9.0
al11ytyw            100.0
am42ybuv              9.0
an89ibyq             24.0
aq28onip             24.0
eb37yzyp              9.0
ep70ujin             22.5
ew73ugaf             82.0
ez72oxib             75.0
fa75kyqy              0.0
fu40panu            100.0
ga45wapo            100.0
go63gaxo             59.0
he09gyta             46.0
he82luta              9.0
hi25numi              1.0
hi60quti             22.5
ib35olyr             82.0
if21eseh              9.0
if80ajil            100.0
ik94foow             57.0
il71ywod             38.0
ix31ipix              1.0
ja62sysi              9.0
je54luly             53.5
ju47kato             51.0
ku05zuji             62.0
lo27cyru             42.0
ly44qone            100.0
ly87muro            100.0
mo58ruxy              1.0
na30dopa              1.0
ni38doqy             21.0
ok13qina              0.0
pe39toqa             60.0
qe72syka             33.5
ra99topo             19.0
ri32luvi              1.0
ro54hiqu             80.0
sa58juwu              9.0
sy23hoza              9.0
ta08goje            100.0
tu51vibo             19.0
ty28vipo              0.0
uj46yrof             21.0
uk68ebih             10.5
uk68iduv             85.0
us52odab              0.0
vo28hudo            100.0
we70xebi            100.0
xi46feza             66.5
yh07ajaw             85.0
yp69ejot            100.0
yq13isef              1.0
ys61uqym              9.0
yv49alyr             11.0
yx26enos             19.0
za07ryma             92.0